(function( ){ 	var tp  =  $.fn.tp$  =  $.fn.tp$ || {};	
				var gio =  tp.gio    =  tp.gio   || {};
	
	gio.def.albums['monkeyban']={


		game	:{ basekey		: 'monkeyban' },
		bundle	:
		{
			album_name	: 'Island School',
			collections : [
			{	
				title	:'Intro'
			},

			{
				address	:
				{
					album_key : 'sokoban',
					collection_key : 'grigoriev',
					file_key : 'grigr2002.txt',
				},
				//context_album_key : 'sokoban',
				title :'grigr2002',
				map_title_source	:'comment'
			},
			{	
				address	:
				{
					album_key : 'sokoban',
					collection_key : 'holland',
					file_key : '2008_06_29.txt',
				},
				title: 'David Holland. 2008_06_29.',
				map_title_source	:'title'
			},
			{	
				address	:
				{
					collection_key : 'holland_solutions',
					file_key : '2008_06_29.txt',
				},
				title: 'David Holland. Solutions.'
			}
		]

		},// bundle



		dresses  :
		{ 
			'default' :
			{
				tile	:{ width : 30, height: 30 }
			},
			'monkeban' :
			{

					skin_key : 'monkeyban',
					chosen	: true,
					title	: 'Yard',
					links	:	[
						{title:'<a target="_blank" href="http://www.ne.jp/asahi/ai/yoshio/sokoban/handmade/index.html">Yoshio Murase and Masato Hiramatsu. Handmade.</a>'},
						{title:'<a target="_blank" href="http://www.ne.jp/asahi/ai/yoshio/sokoban/auto52/index.html">Yoshio Murase. Autogenerated.</a>'},
						{title:'<a target="_blank" href="http://www.sourcecode.se/sokoban/levels.php">Possibly enough for one human life ...</a>'},
						{title:'<a target="_blank" href="http://users.bentonrea.com/~sasquatch/sokoban/">Sokoban puzzles by David W. Skinner</a>'}
					],

					//////////////////////// GUI /////////////////////////////////
					tile	:{ width : 30, height: 30 },
					style	:{	play:{
										backgroundImage:'background.png',
										backgroundColor:''
								},
						},			
					//////////////////////// GUI END /////////////////////////////////

					//////////////////////// INFO /////////////////////////////////
					//Has one macro: <%game.nam%>
					rules	:
						"The schoolkeeper can push monkey, but cannot pull.\n"+
						"Schoolkeeper cannot push two monkeys.\n"+
						"Monkeys who are in contact with the pushed fellow\n"+
						"will do the same move whenever possible.\n"+
						"Monkeys can run over chairs and schoolkeeper learned do the same from them.\n",

					objective:
						"Put each monkey into class chair",

					story:
						"It's hard to take classes in summer time ... that's why these monkeys\n"+
						"at large ... Help bring them back to learning ...\n",


					credits:
						"Sokoban game has been invented by Hiroyuki Imabayashi in 1981. Look in Wikipedia for detailed history.\n\n" +

						"Blue Man Picture. Shared by: OCAL 04-Aug-08,\n"+
						"   profile: www.clker.com/profile-1068.html\n"+
						"   downloaded from: www.clker.com/clipart-man-standing-1.html\n\n"+

						"Monkey Picture. Shared by: Shopper 22-Jul-11,\n"+
						"   profile: www.clker.com/profile-103806.html,\n"+
						"   downloaded from: www.clker.com/clipart-monkey-12.html\n\n"+

						"Sofa Picture. Shared by: OCAL 21-Oct-10,\n"+
						"   profile: www.clker.com/profile-1068.html,\n"+
						"   downloaded from: www.clker.com/clipart-sofa-2.html\n\n"+

						"This game, #%game.nam%#, skin design, art, and story is Copyright (c) 2011 Landkey.net. All rights reserved.\n",
		
						//////////////////////// INFO END /////////////////////////////////


						//////////////// mask with human names ... ///////////////////////
						hname_table	:{ //optional
							hero_x	: 'klasskeeper',
							box_x	: 'monkey'
						},
						///////////////////////////////////////////////////////////////////

						image_decoder	:{
							'hero_x':'portablejim_Man_Standing_OCAL_2008_www.openclipart.org.png',
							'box_x':'shopper_2011_monkey-md.png',
							'wall_x':'wall_674c.png',
							'target_x':'target_x.png',
							'ground_x':''
						}
			}// monkeban

		}// dresses

	};


})();


