(function( $ ){ 	var tp  =  $.fn.tp$  =  $.fn.tp$ || {};	
					var gio =  tp.gio    =  tp.gio   || {};
	
	var key='colorban';
	gio.config[key]={
		basekey		: 'colorban_abstract',
		isabstract	: false,
		key			: key,
		path 		: 'games/'+key,
		collections : [
				{	path: key+'/kirillov/colored_soko.txt',
				title				: 'Colored Soko',
				map_title_source	:'title'
				},
				{	path: key+'/kirillov/intro.txt',
					title				: 'Introduction Demo',
					map_title_source	:'title'
				}
		],
		default_collection_ix	:0,
		links	:	[
			{title:'<a href="http://www.ne.jp/asahi/ai/yoshio/sokoban/handmade/index.html">Yoshio Murase and Masato Hiramatsu. Handmade.</a>'},
			{title:'<a href="http://www.ne.jp/asahi/ai/yoshio/sokoban/auto52/index.html">Yoshio Murase. Autogenerated.</a>'},
			{title:'<a href="http://www.sourcecode.se/sokoban/levels.php">Possibly enough for one human life ...</a>'},
			{title:'<a href="http://users.bentonrea.com/~sasquatch/sokoban/">Sokoban puzzles by David W. Skinner</a>'}
		]
	};


})(jQuery);


