(function( ){ 	var tp  =  $.fn.tp$  =  $.fn.tp$ || {};	
				var gio =  tp.gio    =  tp.gio   || {};



	
	gio.def.albums['monkeyban']={


		gkey		: 'monkeyban' ,
		album_name	: 'Island School',


		collections	: [


				{	"ckey" : "beginner", "credits" : {	"title"		: "Beginner" 	}  },

				{	"list_title"	: "Microban",		"ref" : { "folder" : { "fkey": "monkey_microban1.txt" }  } },

				{	"list_title"	: "Unexplored. D. W. Skinner. Microban.",			"ref" : { "folder" : { "akey" : "sokoban", "fkey": "microban1.txt",	"ckey": "skinner" }  } },
				{	"list_title"	: "Unexplored. D. W. Skinner. Microban II.",		"ref" : { "folder" : { "akey" : "sokoban", "fkey": "microban2.txt",	"ckey": "skinner" }  } },
				{	"list_title"	: "Unexplored. D. W. Skinner. Microban III.",		"ref" : { "folder" : { "akey" : "sokoban", "fkey": "microban3.txt",	"ckey": "skinner" }  } },
				{	"list_title"	: "Unexplored. D. W. Skinner. Microban IV.",		"ref" : { "folder" : { "akey" : "sokoban", "fkey": "microban4.txt",	"ckey": "skinner" }  } },
				{	"list_title"	: "Unexplored. D. W. Skinner. Microban V.",			"ref" : { "folder" : { "akey" : "sokoban", "fkey": "microban5.txt",	"ckey": "skinner" }  } },

				{	"list_title"	: "David Holland. dh1.",							"ref" : { "folder" : {  "akey" : "sokoban", "fkey": "authentic_David_Holland_dh1.txt",	"ckey": "holland" } }, 	"map_title_source"	: "comment" },

				{	"list_title"	: "Unexplored. D. W. Skinner. Sasquatch.",			"ref" : { "folder" : { "akey" : "sokoban", "fkey": "sasquatch1.txt",	"ckey": "skinner" }  } },
				{	"list_title"	: "Unexplored. D. W. Skinner. Sasquatch II.",		"ref" : { "folder" : {  "akey" : "sokoban", "fkey": "sasquatch2.txt",	"ckey": "skinner" }  } },
				{	"list_title"	: "Unexplored. D. W. Skinner. Sasquatch III.",		"ref" : { "folder" : { "akey" : "sokoban", "fkey": "sasquatch3.txt",	"ckey": "skinner" }  } },
				{	"list_title"	: "Unexplored. D. W. Skinner. Sasquatch IV.", 		"ref" : { "folder" : { "akey" : "sokoban", "fkey": "sasquatch4.txt",	"ckey": "skinner" }  } },
				{	"list_title"	: "Unexplored. D. W. Skinner. Sasquatch V.", 		"ref" : { "folder" : { "akey" : "sokoban", "fkey": "sasquatch5.txt",	"ckey": "skinner" }  } },
				{	"list_title"	: "Unexplored. D. W. Skinner. Sasquatch VI.",		"ref" : { "folder" : { "akey" : "sokoban", "fkey": "sasquatch6.txt",	"ckey": "skinner" }  } },
				{	"list_title"	: "Unexplored. D. W. Skinner. Sasquatch VII.",		"ref" : { "folder" : { "akey" : "sokoban", "fkey": "sasquatch7.txt",	"ckey": "skinner" }  } },
				{	"list_title"	: "Unexplored. D. W. Skinner. Sasquatch VIII.",		"ref" : { "folder" : { "akey" : "sokoban", "fkey": "sasquatch8.txt",	"ckey": "skinner" }  } },
				{	"list_title"	: "Unexplored. D. W. Skinner. Sasquatch IX.",		"ref" : { "folder" : { "akey" : "sokoban", "fkey": "sasquatch9.txt",	"ckey": "skinner" }  } },
				{	"list_title"	: "Unexplored. D. W. Skinner. Sasquatch X.",		"ref" : { "folder" : { "akey" : "sokoban", "fkey": "sasquatch10.txt",	"ckey": "skinner" }  } },
				{	"list_title"	: "Unexplored. D. W. Skinner. Sasquatch XI.",		"ref" : { "folder" : { "akey" : "sokoban", "fkey": "sasquatch11.txt",	"ckey": "skinner" }  } },
				{	"list_title"	: "Unexplored. D. W. Skinner. Sasquatch XII.",		"ref" : { "folder" : { "akey" : "sokoban", "fkey": "sasquatch12.txt",	"ckey": "skinner" }  } },


				{
					"ref" : { "folder" : {	"akey" : "sokoban", ckey: 'grigoriev', fkey: 'grigr2001.txt' } },
					credits : { "title" : "Unexplored. Evgeny Grigoriev. 2001." },
					map_title_source :'comment'
				},

				{
					"ref" : { "folder" : {	"akey" : "sokoban", ckey: 'grigoriev', fkey: 'grigr2002.txt' } },
					credits : { "title"		: "Unexplored. Evgeny Grigoriev. 2002." },
					map_title_source	:'comment'
				}

		],


		dresses  :
		{ 
			'default' :
			{
				tile	:{ width : 30, height: 30 }
			},

			'monkeyban' :
			{

					skin_key : 'monkeyban',
					chosen	: true,


					credits : {
						"title"		: "Yard",
						"copyright"	: "Copyright (C) 2012 Konstantin Kirillov",
						"license"	: "host-based",
						"web_site"	: "http://landkey.net/gio/gio/play",
						"date"		: "November 2 2012",
						"email"		: "beaverscript (a) landkey (.) net"
					},


					links	:	[
						{title:'<a target="_blank" href="http://www.ne.jp/asahi/ai/yoshio/sokoban/handmade/index.html">Yoshio Murase and Masato Hiramatsu. Handmade.</a>'},
						{title:'<a target="_blank" href="http://www.ne.jp/asahi/ai/yoshio/sokoban/auto52/index.html">Yoshio Murase. Autogenerated.</a>'},
						{title:'<a target="_blank" href="http://www.sourcecode.se/sokoban/levels.php">Possibly enough for one human life ...</a>'},
						{title:'<a target="_blank" href="http://users.bentonrea.com/~sasquatch/sokoban/">Sokoban puzzles by David W. Skinner</a>'}
					],

					//////////////////////// GUI /////////////////////////////////
					tile	:{ width : 40, height: 40 },
					style	:{	play:{
										backgroundImage:'background.png',
										backgroundColor:''
								},
						},			
					//////////////////////// GUI END /////////////////////////////////

					//////////////////////// INFO /////////////////////////////////
					rules	:
						"The schoolkeeper is not dexterous to pull monkey, but can push it.\n"+
						"Monkeys in contact with the moved fellow\n"+
						"will do the same move whenever possible.\n"+
						"Monkeys can run over chairs and schoolkeeper\nlearned do the same from them.\n",

					objective:
						"Put each monkey into class chair",

					story:
						"It's hard to take classes in summer time ... that's why these monkeys\n"+
						"at large ... Help bring them back to learning ...\n",
		
						//////////////////////// INFO END /////////////////////////////////


						//////////////// mask with human names ... ///////////////////////
						hname_table	:{ //optional
							hero_x	: 'klasskeeper',
							box_x	: 'monkey'
						},
						///////////////////////////////////////////////////////////////////

						image_decoder	:{
							'hero_x':'portablejim_Man_Standing_OCAL_2008_www.openclipart.org.png',
							'ground_b' : 'ground_x.png'
						}
			}// monkeban

		}// dresses

	};


})();


