(function( $ ){ 	var tp  =  $.fn.tp$  =  $.fn.tp$ || {};	
					var gio =  tp.gio    =  tp.gio   || {};
	
	var key='tokenban';
	gio.config[key]={
		nam			: 'Tokenban',
		basekey		: 'colorban_abstract',
		isabstract	: false,
		key			: key,
		path 		: 'games/'+key,
		img_path	: 'games/'+key+'/img',
		collections : [
			{	path: key+'/kirillov/colored_soko.txt',
				title				: 'Colored Soko',
				map_title_source	:'title'
			}
		],
		default_collection_ix	:0,
		links	:	[
			{title:'<a href="http://www.ne.jp/asahi/ai/yoshio/sokoban/handmade/index.html">Yoshio Murase and Masato Hiramatsu. Handmade.</a>'},
			{title:'<a href="http://www.ne.jp/asahi/ai/yoshio/sokoban/auto52/index.html">Yoshio Murase. Autogenerated.</a>'},
			{title:'<a href="http://www.sourcecode.se/sokoban/levels.php">Possibly enough for one human life ...</a>'},
			{title:'<a href="http://users.bentonrea.com/~sasquatch/sokoban/">Sokoban puzzles by David W. Skinner</a>'}
		],

		post_definition : (function(game){
			var itr=game.interact;
			for(var i=1; i<game.colors.length; i++){
				var b=game.box[i];
				game.activity_role[b]='active';
				for(var j=1; j<game.colors.length; j++){
					game.interact[b][game.box[j]]='swap';
				}
				game.areal[b]='box_x';	
			}
			//No goal to deliver cart to a target:
			delete game.baton.box_x
		})
	};

	

})(jQuery);


