(function( ){ 	var tp  =  $.fn.tp$  =  $.fn.tp$ || {};	
				var gio =  tp.gio    =  tp.gio   || {};



	
	gio.def.albums['monkeyban']={


		gkey		: 'monkeyban' ,
		album_name	: 'Island School',


		collections	: [


				{	"credits" : {	"title"		: "Intro" 	}  },


				{	"title"	: "Unexplored. D. W. Skinner. Sasquatch.", "address"		:{ "akey" : "sokoban", "fkey": "sasquatch1.txt",	"ckey": "skinner",  }, 	"map_title_source"	: "title"  },
				{	"title"	: "Unexplored. D. W. Skinner. Sasquatch II.", "address"	:{ "akey" : "sokoban", "fkey": "sasquatch2.txt",	"ckey": "skinner",  }, 	"map_title_source"	: "title"  },
				{	"title"	: "Unexplored. D. W. Skinner. Sasquatch III.", "address"	:{ "akey" : "sokoban", "fkey": "sasquatch3.txt",	"ckey": "skinner",  }, 	"map_title_source"	: "title"  },
				{	"title"	: "Unexplored. D. W. Skinner. Sasquatch IV.", "address"	:{ "akey" : "sokoban", "fkey": "sasquatch4.txt",	"ckey": "skinner",  }, 	"map_title_source"	: "title"  },
				{	"title"	: "Unexplored. D. W. Skinner. Sasquatch V.", "address"	:{ "akey" : "sokoban", "fkey": "sasquatch5.txt",	"ckey": "skinner",  }, 	"map_title_source"	: "title"  },
				{	"title"	: "Unexplored. D. W. Skinner. Sasquatch VI.", "address"	:{ "akey" : "sokoban", "fkey": "sasquatch6.txt",	"ckey": "skinner",  }, 	"map_title_source"	: "title"  },
				{	"title"	: "Unexplored. D. W. Skinner. Sasquatch VII.", "address"	:{ "akey" : "sokoban", "fkey": "sasquatch7.txt",	"ckey": "skinner",  }, 	"map_title_source"	: "title"  },
				{	"title"	: "Unexplored. D. W. Skinner. Sasquatch VIII.", "address"	:{ "akey" : "sokoban", "fkey": "sasquatch8.txt",	"ckey": "skinner",  }, 	"map_title_source"	: "title"  },
				{	"title"	: "Unexplored. D. W. Skinner. Sasquatch IX.", "address"	:{ "akey" : "sokoban", "fkey": "sasquatch9.txt",	"ckey": "skinner",  }, 	"map_title_source"	: "title"  },
				{	"title"	: "Unexplored. D. W. Skinner. Sasquatch X.", "address"	:{ "akey" : "sokoban", "fkey": "sasquatch10.txt",	"ckey": "skinner",  }, 	"map_title_source"	: "title"  },
				{	"title"	: "Unexplored. D. W. Skinner. Sasquatch XI.", "address"	:{ "akey" : "sokoban", "fkey": "sasquatch11.txt",	"ckey": "skinner",  }, 	"map_title_source"	: "title"  },
				{	"title"	: "Unexplored. D. W. Skinner. Sasquatch XII.", "address"	:{ "akey" : "sokoban", "fkey": "sasquatch12.txt",	"ckey": "skinner",  }, 	"map_title_source"	: "title"  },


				{	"title"	: "Unexplored. D. W. Skinner. Microban.", "address"		:{ "akey" : "sokoban", "fkey": "microban1.txt",	"ckey": "skinner",  }, 	"map_title_source"	: "title"  },
				{	"title"	: "Unexplored. D. W. Skinner. Microban II.", "address"	:{ "akey" : "sokoban", "fkey": "microban2.txt",	"ckey": "skinner",  }, 	"map_title_source"	: "title"  },
				{	"title"	: "Unexplored. D. W. Skinner. Microban III.", "address"	:{ "akey" : "sokoban", "fkey": "microban3.txt",	"ckey": "skinner",  }, 	"map_title_source"	: "title"  },
				{	"title"	: "Unexplored. D. W. Skinner. Microban IV.", "address"	:{ "akey" : "sokoban", "fkey": "microban4.txt",	"ckey": "skinner",  }, 	"map_title_source"	: "title"  },
				{	"title"	: "Unexplored. D. W. Skinner. Microban V.", "address"		:{ "akey" : "sokoban", "fkey": "microban5.txt",	"ckey": "skinner",  }, 	"map_title_source"	: "title"  },



				{
					credits : { "title"		: "Unexplored. Evgeny Grigoriev. 2001." },
					address	:{	"akey" : "sokoban", 
								ckey: 'grigoriev',
								fkey: 'grigr2001.txt'
							},
					map_title_source	:'comment'
				},

				{
					credits : { "title"		: "Unexplored. Evgeny Grigoriev. 2002." },
					address	:{	"akey" : "sokoban",
								ckey: 'grigoriev',
								fkey: 'grigr2002.txt'
							},
					map_title_source	:'comment'
				}

		],


		dresses  :
		{ 
			'default' :
			{
				tile	:{ width : 30, height: 30 }
			},

			'monkeban' :
			{

					skin_key : 'monkeyban',
					chosen	: true,
					title	: 'Yard',


					credits : {
						"author"	: "Konstantin Kirillov",
						"copyright"	: "Copyright (C) 2012 Konstantin Kirillov",
						"license"	: "host-based",
						"web_site"	: "http://landkey.net/gio/gio/play",
						"date"		: "November 2 2012",
						"email"		: "beaverscript (a) landkey (.) net"
					},


					links	:	[
						{title:'<a target="_blank" href="http://www.ne.jp/asahi/ai/yoshio/sokoban/handmade/index.html">Yoshio Murase and Masato Hiramatsu. Handmade.</a>'},
						{title:'<a target="_blank" href="http://www.ne.jp/asahi/ai/yoshio/sokoban/auto52/index.html">Yoshio Murase. Autogenerated.</a>'},
						{title:'<a target="_blank" href="http://www.sourcecode.se/sokoban/levels.php">Possibly enough for one human life ...</a>'},
						{title:'<a target="_blank" href="http://users.bentonrea.com/~sasquatch/sokoban/">Sokoban puzzles by David W. Skinner</a>'}
					],

					//////////////////////// GUI /////////////////////////////////
					tile	:{ width : 40, height: 40 },
					style	:{	play:{
										backgroundImage:'background.png',
										backgroundColor:''
								},
						},			
					//////////////////////// GUI END /////////////////////////////////

					//////////////////////// INFO /////////////////////////////////
					rules	:
						"The schoolkeeper is not dexterous to pull monkey, but can push it.\n"+
						"Monkeys in contact with the moved fellow\n"+
						"will do the same move whenever possible.\n"+
						"Monkeys can run over chairs and schoolkeeper\nlearned do the same from them.\n",

					objective:
						"Put each monkey into class chair",

					story:
						"It's hard to take classes in summer time ... that's why these monkeys\n"+
						"at large ... Help bring them back to learning ...\n",
		
						//////////////////////// INFO END /////////////////////////////////


						//////////////// mask with human names ... ///////////////////////
						hname_table	:{ //optional
							hero_x	: 'klasskeeper',
							box_x	: 'monkey'
						},
						///////////////////////////////////////////////////////////////////

						image_decoder	:{
							'hero_x':'portablejim_Man_Standing_OCAL_2008_www.openclipart.org.png',
							'ground_x':''
						}
			}// monkeban

		}// dresses

	};


})();


