(function(){ 	var tp  =  $.fn.tp$  =  $.fn.tp$ || {};	
				var gio =  tp.gio    =  tp.gio   || {};
	
	gio.def.albums['colorban']={


		game	:{ basekey	: 'colorban' },
		bundle	:
		{
			collections :
			[
				{	address	:
					{
						file_key : 'colored_soko.txt',
					},
					title				: 'Colored Soko',
					map_title_source	:'title'
				},
				{	address	:
					{
						file_key : 'intro.txt',
					},
					title				: 'Introduction Demo',
					map_title_source	:'title'
				}
			]
		},// bundle


		dresses  :  { 'default' :
			{

				links	:	[
					{title:'<a href="http://www.ne.jp/asahi/ai/yoshio/sokoban/handmade/index.html">Yoshio Murase and Masato Hiramatsu. Handmade.</a>'},
					{title:'<a href="http://www.ne.jp/asahi/ai/yoshio/sokoban/auto52/index.html">Yoshio Murase. Autogenerated.</a>'},
					{title:'<a href="http://www.sourcecode.se/sokoban/levels.php">Possibly enough for one human life ...</a>'},
					{title:'<a href="http://users.bentonrea.com/~sasquatch/sokoban/">Sokoban puzzles by David W. Skinner</a>'}
				],


				// GUI:
				style	:{	play:	{
										"backgroundImage": "",
										"backgroundColor": "#666666"
									}
						}
	
			}// default
		}// dresses
	};


})();


