(function( ){ 	var tp  =  $.fn.tp$  =  $.fn.tp$ || {};	
				var gio =  tp.gio    =  tp.gio   || {};


	// //\\//	This file is a part of documentation. 
	//			Not a file included in source code.
	
	gio.def.albums['monkeyban']={


		gkey	: 'monkeyban' ,
		album_name	: 'Island School',
		collections : [

			{	
				"credits" : {	"author"	: "Authors credited for each map separately",
								"title"		: "Intro",
								"license"	: "Each map is licensed separately."
				}
			},






				{	
					credits : { "author"	: "David W Skinner",
								"title"		: "Microban V (26 puzzles, October 2010, this set is unfinished)",
								"copyright" : "Copyright (c) 2010 David W Skinner",
								"license"	: "The sets Sasquatch and Microban may be freely distributed provided they remain properly credited.",
								"web_site"	: "http://users.bentonrea.com/~sasquatch/sokoban/",
								"email"		: "s a s q u a t c h (a) b e n t o n r e a . c o m"
							  },
					external			:{	
											link : 'http://users.bentonrea.com/~sasquatch/sokoban/m5'
										},
					map_title_source	: 'title'
				},


















			{	
				// referres to "collection object" from possibly alien album definition 
				//			(hence, referres to undressed album)
				"ref" : {	"akey" : "sokoban",
							"ix"	: 0
				}				
			},

			{
				credits : { "title"		: "Unexplored. Evgeny Grigoriev. 2001." },

				// referres to "collection file" from possibly alien album folder
				address	:{	"akey" : "sokoban", 
							ckey: 'grigoriev',
							fkey: 'grigr2001.txt'
						},
				map_title_source	:'comment'
			}

		],


		dresses  :
		{ 
			'default' :
			{
				tile	:{ width : 30, height: 30 }
			},
			'monkeban' :
			{

					skin_key : 'monkeyban',
					chosen	: true,
					title	: 'Yard',


					credits : {
						"author"	: "Konstantin Kirillov",
						"copyright"	: "Copyright (C) 2012 Konstantin Kirillov",
						"license"	: "host-based",
						"web_site"	: "http://landkey.net/gio/gio/play",
						"date"		: "November 2 2012",
						"email"		: "beaverscript (a) landkey (.) net"
					},


					links	:	[
						{title:'<a target="_blank" href="http://www.ne.jp/asahi/ai/yoshio/sokoban/handmade/index.html">Yoshio Murase and Masato Hiramatsu. Handmade.</a>'},
						{title:'<a target="_blank" href="http://www.ne.jp/asahi/ai/yoshio/sokoban/auto52/index.html">Yoshio Murase. Autogenerated.</a>'},
						{title:'<a target="_blank" href="http://www.sourcecode.se/sokoban/levels.php">Possibly enough for one human life ...</a>'},
						{title:'<a target="_blank" href="http://users.bentonrea.com/~sasquatch/sokoban/">Sokoban puzzles by David W. Skinner</a>'}
					],

					//////////////////////// GUI /////////////////////////////////
					tile	:{ width : 30, height: 30 },
					style	:{	play:{
										backgroundImage:'background.png',
										backgroundColor:''
								},
						},			
					//////////////////////// GUI END /////////////////////////////////

					//////////////////////// INFO /////////////////////////////////
					rules	:
						"The schoolkeeper is not dexterous to pull monkey, but can push it.\n"+
						"Monkeys in contact with the moved fellow\n"+
						"will do the same move whenever possible.\n"+
						"Monkeys can run over chairs and schoolkeeper\nlearned do the same from them.\n",

					objective:
						"Put each monkey into class chair",

					story:
						"It's hard to take classes in summer time ... that's why these monkeys\n"+
						"at large ... Help bring them back to learning ...\n",
		
						//////////////////////// INFO END /////////////////////////////////


						//////////////// mask with human names ... ///////////////////////
						hname_table	:{ //optional
							hero_x	: 'klasskeeper',
							box_x	: 'monkey'
						},
						///////////////////////////////////////////////////////////////////

						image_decoder	:{
							'hero_x':'portablejim_Man_Standing_OCAL_2008_www.openclipart.org.png',
							'ground_x':''
						}
			}// monkeban

		}// dresses

	};


})();


