(function(){ 	var tp  =  $.fn.tp$  =  $.fn.tp$ || {};	
				var gio =  tp.gio    =  tp.gio   || {};


	
	gio.def.albums['sokoban'] =
	{
			collections :[

				{	"title"	: "David Holland. dh1.", "address"		:{ "fkey": "authentic_David_Holland_dh1.txt",	"ckey": "holland",  }, 	"map_title_source"	: "title"  },

				{	"title"	: "David W Skinner. Microban.", "address"		:{ "fkey": "microban1.txt",	"ckey": "skinner",  }, 	"map_title_source"	: "title"  },
				{	"title"	: "David W Skinner. Microban II.", "address"	:{ "fkey": "microban2.txt",	"ckey": "skinner",  }, 	"map_title_source"	: "title"  },
				{	"title"	: "David W Skinner. Microban III.", "address"	:{ "fkey": "microban3.txt",	"ckey": "skinner",  }, 	"map_title_source"	: "title"  },
				{	"title"	: "David W Skinner. Microban IV.", "address"	:{ "fkey": "microban4.txt",	"ckey": "skinner",  }, 	"map_title_source"	: "title"  },
				{	"title"	: "David W Skinner. Microban V.", "address"		:{ "fkey": "microban5.txt",	"ckey": "skinner",  }, 	"map_title_source"	: "title"  },


				{	
					credits : { "author"	: "David W Skinner",
								"title"		: "Microban V (26 puzzles, October 2010, this set is unfinished)",
								"copyright" : "Copyright (c) 2010 David W Skinner",
								"license"	: "The sets Sasquatch and Microban may be freely distributed provided they remain properly credited.",
								"web_site"	: "http://users.bentonrea.com/~sasquatch/sokoban/",
								"email"		: "s a s q u a t c h (a) b e n t o n r e a . c o m"
							  },
					external			:{	
											link : 'http://users.bentonrea.com/~sasquatch/sokoban/m5'
										},
					map_title_source	: 'title'
				},



				{	"title"	: "David W Skinner. Sasquatch.", "address"	:{ "fkey": "sasquatch1.txt",	"ckey": "skinner",  }, 	"map_title_source"	: "title"  },
				{	"title"	: "David W Skinner. Sasquatch II.", "address"	:{ "fkey": "sasquatch2.txt",	"ckey": "skinner",  }, 	"map_title_source"	: "title"  },
				{	"title"	: "David W Skinner. Sasquatch III.", "address"	:{ "fkey": "sasquatch3.txt",	"ckey": "skinner",  }, 	"map_title_source"	: "title"  },
				{	"title"	: "David W Skinner. Sasquatch IV.", "address"	:{ "fkey": "sasquatch4.txt",	"ckey": "skinner",  }, 	"map_title_source"	: "title"  },
				{	"title"	: "David W Skinner. Sasquatch V.", "address"	:{ "fkey": "sasquatch5.txt",	"ckey": "skinner",  }, 	"map_title_source"	: "title"  },
				{	"title"	: "David W Skinner. Sasquatch VI.", "address"	:{ "fkey": "sasquatch6.txt",	"ckey": "skinner",  }, 	"map_title_source"	: "title"  },
				{	"title"	: "David W Skinner. Sasquatch VII.", "address"	:{ "fkey": "sasquatch7.txt",	"ckey": "skinner",  }, 	"map_title_source"	: "title"  },
				{	"title"	: "David W Skinner. Sasquatch VIII.", "address"	:{ "fkey": "sasquatch8.txt",	"ckey": "skinner",  }, 	"map_title_source"	: "title"  },
				{	"title"	: "David W Skinner. Sasquatch IX.", "address"	:{ "fkey": "sasquatch9.txt",	"ckey": "skinner",  }, 	"map_title_source"	: "title"  },
				{	"title"	: "David W Skinner. Sasquatch X.", "address"	:{ "fkey": "sasquatch10.txt",	"ckey": "skinner",  }, 	"map_title_source"	: "title"  },
				{	"title"	: "David W Skinner. Sasquatch XI.", "address"	:{ "fkey": "sasquatch11.txt",	"ckey": "skinner",  }, 	"map_title_source"	: "title"  },
				{	"title"	: "David W Skinner. Sasquatch XII.", "address"	:{ "fkey": "sasquatch12.txt",	"ckey": "skinner",  }, 	"map_title_source"	: "title"  },


			{
				credits : { "title"		: "Evgeny Grigoriev. 2001." },
				address	:{	ckey: 'grigoriev',
							fkey: 'grigr2001.txt'
						},
				map_title_source	:'comment'
			},

			{
				credits : { "title"		: "Evgeny Grigoriev. 2002." },
				address	:{	ckey: 'grigoriev',
							fkey: 'grigr2002.txt'
						},
				map_title_source	:'comment'
			},



			{
				credits : { "title"		: "Weirdy" 	},
				address	:{	ckey: 'wierdy' },
				map_title_source	:'comment'
			}

			],


		dresses  :  { 'default' :
			{


				links	:	[
					{title:'<a target="_blank" href="http://www.ne.jp/asahi/ai/yoshio/sokoban/handmade/index.html">Yoshio Murase and Masato Hiramatsu. Handmade.</a>'},
					{title:'<a target="_blank" href="http://www.ne.jp/asahi/ai/yoshio/sokoban/auto52/index.html">Yoshio Murase. Autogenerated.</a>'},
					{title:'<a target="_blank" href="http://www.sourcecode.se/sokoban/levels.php">Possibly enough for one human life ...</a>'},
					{title:'<a target="_blank" href="http://users.bentonrea.com/~sasquatch/sokoban/">Sokoban puzzles by David W. Skinner</a>'},
					{title:'<a target="_blank" href="http://sneezingtiger.com/sokoban/levels.html">Some Levels</a>'},
					{title:'<a target="_blank" href="http://www.sneezingtiger.com/sokoban/levels/yoshioText.html">Non Researched Source</a>'},
					{title:'<a target="_blank" href="http://sokoban.ws/">MF8 Sokoban Competition</a>'}
				],

				rules: 	"robot can push a box",
				objective: 	"push all boxes into black cells",
				story: 	"Our Hero, the robot, walks through the maze and pushes the boxes to dark cells."

			}// default
		}// dresses
	};

})();


