(function( $ ){ 	var tp  =  $.fn.tp$  =  $.fn.tp$ || {};	
					var gio =  tp.gio    =  tp.gio   || {};
	
	var key='sokoban';
	gio.config[key]={
		nam			: 'Sokoban',
		basekey		: 'colorban_abstract',
		isabstract	: false,
		key			: key,
		path 		: 'games/'+key,
		collections : [
			{
				path: key+'/grigoriev/grigr2002.txt', 
				map_title_source	:'comment'
			},
			{	path: key+'/holland/2008_06_29.txt',
				title: 'David Holland. 2008_06_29.',
				map_title_source	:'title'
			},

			{	
				external			:{	human_readable : 'http://sneezingtiger.com/sokoban/levels/yoshioText.html',
										link : 'http://sneezingtiger.com/sokoban/levels/yoshioText.html',
										title : 'Yoshio Murase'
									},
				map_title_source	: 'title'
			},

			{	
				external			:{	human_readable : 'http://users.bentonrea.com/~sasquatch/sokoban/',

										// for debug:
										// link : 'http://localhost/bspir/play/server/slow_connection_emulator.php',

										link : 'http://users.bentonrea.com/~sasquatch/sokoban/s2',
										title : 'Sasquatch II' //(August, 1999) does not fit
									},
				map_title_source	: 'title'
			},

/*

			{	external_link		: 'http://users.bentonrea.com/~sasquatch/sokoban/s3',
				human_readable_page	: 'http://users.bentonrea.com/~sasquatch/sokoban/',
				title				: '<span style="color:#00FF00">Try external link: Sasquatch III (June, 2000)</span>'+
										' <a href="http://users.bentonrea.com/~sasquatch/sokoban/s3" style="color:#FFAAAA">Text</a>',
				map_title_source	: 'title'
			},
			{	external_link		: 'http://www.sourcecode.se/sokoban/levtext.php?file=100Boxes.slc',
				human_readable_page	: 'http://www.sourcecode.se/sokoban/levels.php',
				title				: '<span style="color:#00FF00">Try external link: Francois Marques</span>'+
										' <a href="http://www.sourcecode.se/sokoban/levtext.php?file=100Boxes.slc" style="color:#FFAAAA">Text</a>',
				map_title_source	: 'title'
			}

	*/	],
		default_collection_ix	:0,
		links	:	[
			{title:'<a target="_blank" href="http://www.ne.jp/asahi/ai/yoshio/sokoban/handmade/index.html">Yoshio Murase and Masato Hiramatsu. Handmade.</a>'},
			{title:'<a target="_blank" href="http://www.ne.jp/asahi/ai/yoshio/sokoban/auto52/index.html">Yoshio Murase. Autogenerated.</a>'},
			{title:'<a target="_blank" href="http://www.sourcecode.se/sokoban/levels.php">Possibly enough for one human life ...</a>'},
			{title:'<a target="_blank" href="http://users.bentonrea.com/~sasquatch/sokoban/">Sokoban puzzles by David W. Skinner</a>'},
			{title:'<a target="_blank" href="http://sneezingtiger.com/sokoban/levels.html">Some Levels</a>'},
			{title:'<a target="_blank" href="http://www.sneezingtiger.com/sokoban/levels/yoshioText.html">Non Researched Source</a>'},
			{title:'<a target="_blank" href="http://sokoban.ws/">MF8 Sokoban Competition</a>'}
		],

		img_path	: 'games/'+key+'/img',

		rules:
			"robot can push a box",

		objective:
			"push all boxes into black cells",

		story:
			"Our Hero, the robot, walks through the maze and pushes the boxes to dark cells.",

		credits:
			"Sokoban game has been invented by Hiroyuki Imabayashi in 1981. Look in Wikipedia for detailed history.\n" +
			"Skin design, art, and story of this implementation of #%game.nam%# is Copyright (c) 2012 Konstantin Kirillov under MIT license.\n"

	};


})(jQuery);


